apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  annotations:
    # Provisioned through the storage ssd provisioner
    # Note: this is created via storage-class.yaml
    volume.beta.kubernetes.io/storage-class: fast
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

